run:
  timeout: 1m
  tests: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - errcheck
    - exhaustive
    - exportloopref
    - gocognit
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - goheader
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - durationcheck
    - forbidigo
    - forcetypeassert
    - ifshort
    - importas
    - nilerr
    - predeclared
    - thelper
    - tparallel
    - wastedassign
    - promlinter
    - bodyclose
    - funlen
    - gocritic
    - prealloc
    # - godot
    # - nlreturn
    - unparam

issues:
  exclude-rules:
    - path: (_test\.go|tests)
      linters:
        - bodyclose
        - dupl
        - funlen
        - goerr113
        - gosec
        - noctx
        - unparam
    - path: (internal/transport/rest)
      linters:
        - godot
