version: "3.9"

services:
  api:
    image: noter:backend
    container_name: noter-backend
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432

  postgres:
    image: postgres:14
    container_name: noter-postgres
    environment:
      POSTGRES_DB: "noter"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
