http:
  port: 8000
  max_header_bytes: 1
  read_timeout: 10s
  write_timeout: 10s

cache:
  ttl: 3600s

postgres:
  dbname: noter
  sslmode: disable

pagination:
  page_size: 100

jwt:
  access_token_ttl: 2h
  refresh_token_ttl: 720h # 30 days
