http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 3600s

postgres:
  dbname: noter
  sslmode: disable

pagination:
  page_size: 100

jwt:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days
